#!/usr/bin/env bash

# install required packages
apt-get install git -y
apt-get install python3-pil -y
apt-get install python3-smbus -y
apt-get install bc i2c-tools -y

# enable SPI and I2C
raspi-config nonint do_spi 0
raspi-config nonint do_i2c 0

git clone https://github.com/dtreichler/PaPiRus.git
cd PaPiRus
python3 setup.py install    # Install PaPirRus python library
papirus-setup    # Install drivers and setup epaper
whiptail --msgbox "The system will now reboot" 8 40
reboot
